name: Push PR

on: 
  push:                              
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - '.gitignore'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'docker-compose.override.yml'

jobs:                                
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4     

  test-code:                         
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for testing
        uses: actions/checkout@v4     

      - name: Install Dependencies
        run: npm install              

      - name: Test code
        run: |
          echo "Testing the code"
          npm test